# Generated by Django 3.2.11 on 2022-02-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0002_reminders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevents',
            name='color',
        ),
        migrations.AlterField(
            model_name='calendarevents',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calendarevents',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calendarevents',
            name='timed',
            field=models.DateTimeField(),
        ),
    ]
