# Generated by Django 3.2.11 on 2022-03-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0004_auto_20220301_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'scrapingworkouts',
            },
        ),
    ]
