# Generated by Django 3.2.11 on 2022-03-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0005_scrapingitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapingitem',
            options={},
        ),
    ]
