# Generated by Django 3.2.11 on 2022-03-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0006_alter_scrapingitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingitem',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='scrapingitem',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
