# Generated by Django 3.2.11 on 2022-03-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0007_auto_20220327_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingitem',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
