# Generated by Django 3.2.11 on 2022-03-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0008_scrapingitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminders',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
