# Generated by Django 3.2.11 on 2022-04-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0010_reminders_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminders',
            name='event_id',
            field=models.IntegerField(max_length=255),
        ),
    ]
