# Generated by Django 3.2.11 on 2022-04-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0012_alter_reminders_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminders',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
